### ISSUE TITLE
Change background color?

### ISSUE THREAD

**Issue by mjhorvath** [HazenBabcock/brigl#11]
Is there a way to change the background color of the window? Thanks.

**Comment by HazenBabcock** [comment]
What have you tried so far?

**Comment by HazenBabcock** [comment]
I thought this was three.js option, but I guess it is not. As of now the only way to change this is to edit the brigl.js file, specifically line 1632, `this.renderer.setClearColor( 0xffffff, 1 );`. This should probably be an option along with the lighting color.

**Comment by mjhorvath** [comment]
Adding a texture mapped skybox might be nice too, though I probably wouldn't use it.

**Comment by HazenBabcock** [comment]
I added options for the background and lighting colors.
[Documentation](https://brigl.readthedocs.io/en/latest/options.html)
[Example](https://hazenbabcock.github.io/brigl/colors.html)

Thanks for the suggestion.

**Comment by mjhorvath** [comment]
Very nice, thanks!
