### ISSUE TITLE
Render window too big for container

### ISSUE THREAD

**Issue by mjhorvath** [HazenBabcock/brigl#12]
On my website, I gave the container DIV element a three pixel border around the edges. However, the render window is slightly too large to fit properly in that container.

![three_px_border](https://user-images.githubusercontent.com/17457030/44617544-340e8c80-a832-11e8-8ba8-6f4f1a63aefb.png)

Link: http://isometricland.net/brigl/ldr_androbot.php

Is there a way I can work around this? Thanks.

**Comment by HazenBabcock** [comment]
An outer DIV with a border and a slightly smaller inner DIV for the render window?

**Comment by mjhorvath** [comment]
I tracked down the problem to lines 1686 and 1687 of "brigle.js". You should use something other than `offsetWidth` and `offsetHeight`. For instance, I changed them to `scrollWidth` and `scrollHeight`.

**Comment by HazenBabcock** [comment]
Why try and use `getContentWidth()`? It looks to me like `scrollWidth` and `scrollHeight` are the right things to use here.

[Understanding clientHeight, offsetHeight & scrollHeight](http://usefulangle.com/post/40/javascript-client-height-vs-offset-height-vs-scroll-height)

**Comment by mjhorvath** [comment]
Because you want to subtract the padding amount too, which scrollHeight and clientHeight do not do.

**Comment by HazenBabcock** [comment]
I maybe fixed this using [Element.Layout](http://api.prototypejs.org/dom/Element/Layout/) from prototype.js. It seemed to work in the tests that I did. Maybe you could verify that it works as expected for you?
