### ISSUE TITLE
Use ldconfig.ldr

### ISSUE THREAD

**Issue by billthefish** [HazenBabcock/brigl#15]
It would be nice if brigl used the ldconfig.ldr file for colors instead of the hardcoded colors. This may add some processing time so maybe have a config option?

**Comment by HazenBabcock** [comment]
Does ldconfig.ldr change a lot? For example do people often customize this file? Or maybe it is sufficient to periodically update the brigl colors to the current ldconfig.ldr values?

**Comment by billthefish** [comment]
I doesn’t change super often and while people do customize it’s not really that common. I might be able to throw together a script to host on LDraw.org that returns the file contents in JSON format to avoid having to parse the file. But your periodic update suggestion would probably be better.

**Comment by HazenBabcock** [comment]
I can write a script for this (in Python) and include it in the project.

**Comment by billthefish** [comment]
I think that’s the best option. Awesome.

**Comment by HazenBabcock** [comment]
This is in the `colors_update` branch if you want to take a look at it. I updated `brigl_materials.js` and added a Python script, `ld_config_to_brigl_materials.py` to the tools directory that you can use to create a version of `brigl_materials.js` from a `LDConfig.ldr` file. 

If you just want to check the colors are okay now you could copy the `brigl_materials.js` file out of this branch and use it to replace the one on your server.

**Comment by billthefish** [comment]
Ok. We have a ldconfig update in the works. I'll test when we finalize it.
