### ISSUE TITLE
 Parts list in steps

### ISSUE THREAD

**Issue by thunaer862** [HazenBabcock/brigl#3]
Hello. Thanks for the software.

Is there any way to put the list of parts to be used in each step?

Thank you very much.

**Comment by HazenBabcock** [comment]
You'd have to write something yourself in order to do that. 

This was my attempt: [brigl-view](https://github.com/HazenBabcock/brigl-view)

It works okay in a desktop computer browser but not so well on a tablet as it consumes a lot of resources.

**Comment by HazenBabcock** [comment]
I think this question has been answered.
