### ISSUE TITLE
Rotation method

### ISSUE THREAD

**Issue by mjhorvath** [HazenBabcock/brigl#7]
Could you add latitude/longitude model rotation like in LDView? It is more intuitive IMO.

**Comment by HazenBabcock** [comment]
Sorry, I'm not sure I understand the request. Both viewers seem to rotate the model the same way when you click and drag with the mouse. Can you please clarify?

**Comment by HazenBabcock** [comment]
Thanks for the explanation, I will look into adding it as an option.

**Comment by HazenBabcock** [comment]
I think I have accurately recreated this rotation model. It is available as an option for `BRIGL.BriglContainer()`, see `test/test_latlon_1.html` for an example.

**Comment by HazenBabcock** [comment]
Done, I think..
