### ISSUE TITLE
Latitude/longitude rotation

### ISSUE THREAD

**Issue by mjhorvath** [HazenBabcock/brigl#9]
How do I enable latitude/longitude rotation? Thanks!

**Comment by HazenBabcock** [comment]
Sorry, I forgot to document that. I just fixed this, so see:
[latlon option](https://brigl.readthedocs.io/en/latest/options.html#brigl-briglcontainer)

Also:
`test/test_latlon_1.html`

**Comment by HazenBabcock** [comment]
Resolved?
